### ISSUE TITLE
base options should be set in beforeConstruct

### ISSUE THREAD

**Issue by grdunn** [apostrophecms/apostrophe-link-widgets#4]
```
module.exports = {
  extend: 'apostrophe-widgets',
  label: 'Link',
  beforeConstruct: function(self, options) {
    options.addFields = [
          // etc..
    ]
  }
}
```

this way subclassing or extending and using `addFields` at top level config won't override default fields.

**Comment by boutell** [comment]
Makes sense to me, wanna PR that puppy?

Don't forget it ends like:

`options.addFields [ ... your stuff ... ].concat(options.addFields || [])`

That concat bit at the end allows the overrides down the line that you're looking for.
